kind: pipeline
name : xKernel Compiler
version: rev1.5_template
steps:
 - name: xKernel Compilation
   image: xyzuan/xdocker:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - git clone --depth=1 https://github.com/nexus-projects/nexus_kernel_xiaomi_lmi.git -b beta-1 lmi
     - cd lmi
     - bash .circleci/build.sh